# replace with `bosh status --uuid`
director_uuid: CHANGE_ME
azs:
  - CHANGE_ME
network_name: CHANGE_ME

nginx:
  vm_type: nano
  static_ips: 10.0.0.1
  local_properties:
    ssl_only: false
    grafana:
      https_port: 443


grafana:
  vm_type: micro
  persistent_disk_type: 1024
alertmanager:
  vm_type: micro
  persistent_disk_type: 1024
prometheus:
  vm_type: micro
  persistent_disk_type: 1024

bosh_exporter:
  bosh:
    uaa:
      url: https://BOSH_DIRECTOR:8443
      client_id: prometheus-bosh
      client_secret: prometheus-client-secret
    url: https://BOSH_DIRECTOR
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----

firehose_exporter:
  uaa:
    url: https://uaa.SYSTEM_DOMAIN
    client_id: prometheus-firehose
    client_secret: prometheus-client-secret
  doppler:
    url: wss://doppler.SYSTEM_DOMAIN
  web:
    port: 9186
  skip_ssl_verify: true

cf_exporter:
  cf:
    api_url: https://api.SYSTEM_DOMAIN
    username: prometheus-cf
    password: prometheus-client-secret
  skip_ssl_verify: true

mysqld_exporter:
  mysql:
    address: CHANGE_ME
    username: CHANGE_ME
    password: CHANGE_ME
