- type: replace
  path: /instance_groups/name=prometheus?/vm_type
  value: ((vm_type_small))

- type: replace
  path: /instance_groups/name=prometheus?/networks
  value: ((network))

- type: replace
  path: /instance_groups/name=prometheus?/azs
  value: ((azs))
