# Deployment Name
deployment_name: prometheus

# Operations Manager credentials to set
pcf_opsman_admin_username:
pcf_opsman_admin_password:
opsman_url:

# if you need to use a jumphost to connect to a BOSH Director, provide these details
# (it is often the OpsManager VM)
jumpbox_url:
jumpbox_port:
jumpbox_username:
jumpbox_ssh_key:

# Set to either opsman_bosh or external_bosh. For external BOSH you need to provide the details below
director_for_deployment: opsman_bosh

# If you set director_for_deployment to external_bosh then you need to provide the Director details. Otherwise keep them empty
external_bosh_address:
external_bosh_client:
external_bosh_client_secret:
external_bosh_ca_cert:

# set to something very secure! you won't need to use these passwords at all
uaa_clients_firehose_exporter_secret:
uaa_clients_cf_exporter_secret:
uaa_bosh_exporter_client_secret:

# This will be the admin password to log in to Grafana GUI
grafana_admin_password:
# This will be the admin password to log in to Prometheus GUI
prometheus_admin_password:
# This will be the admin password to log in to Alertmanager GUI
alertmanager_password:

# AZ(s) to deploy to (as defined in the Director configuration)
deploy_azs: [europe-west1-d]
# network to deploy to (as defined in the Director configuration)
deploy_network: [{name: pcf-net}]

# Github token to authenticate with Github. You can generate one at https://github.com/settings/tokens
github_token:

#
# Parameters below are fine if you are just kicking tires
#

# These values work for a small deployment on PCF. Change to adjust resources
deploy_vm_type_micro: micro
deploy_vm_type_small: small

# arbitrary name for this environment (eg. 'prod')
metrics_environment: pcf

skip_ssl_verify: true
